### ISSUE TITLE
Fatal error: Declaration of GravityView_Dashboard_Views_Request::is_view() must...

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/Dashboard-Views#12]
>Fatal error: Declaration of GravityView_Dashboard_Views_Request::is_view() must be compatible with GV\Request::is_view($return_view = true) in C:\Users\rafae\gravityview\app\public\wp-content\plugins\Dashboard-Views-main\class-gravityview-dashboard-views-request.php on line 64

![image](https://user-images.githubusercontent.com/1222472/206310638-30208ea3-3368-4975-87ad-a344261e41ab.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2090947288/45600

**Comment by zackkatz** [comment]
Closed with b91bce4

**Comment by rafaehlers** [comment]
...and now from a Fatal Error, this became a Warning:

![image](https://user-images.githubusercontent.com/1222472/209215946-e0f8dd3b-152c-4cc9-be67-f6d2c5c7ee19.png)

**Comment by rafaehlers** [comment]
https://gravitykit.slack.com/archives/C727B06MB/p1671739610939099

**Comment by zackkatz** [comment]
This was fixed in ca9e2d7
