### ISSUE TITLE
Dashboard Views breaks GravityView pagination links in the frontend

### ISSUE THREAD

**Issue by bennemann** [GravityKit/Dashboard-Views#21]
When the Dashboard Views extension is active, the `?pagenum` parameter is not added to GravityView's pagination links.

Steps to Reproduce:
1. Activate the Dashboard Views extension.
2. Go to the frontend where a View with multiple pages of entries is displayed.
3. Click on pagination links.

**Comment by mrcasual** [comment]
Fixed in [0f40387](https://github.com/GravityKit/Dashboard-Views/commit/0f40387a3d55a824567aece5de550fd76eceb975).
