### ISSUE TITLE
When enabled, breaks links to single entries in non-Dashboard DataTables

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/Dashboard-Views#7]
1. Configure a DataTables View with a link to single entry
2. Visit on the frontend
3. Enable Dashboard Views
4. The link points to the Dashboard View instead of the DataTables View

The issue is that the admin-ajax request is being seen as an admin request by Dashboard Views…

**Comment by mrcasual** [comment]
@zackkatz, is this still an issue?

Test site: https://app.instawp.io/wordpress-auto-login?site=%242y%2410%240pLp2Ec2kfw4J3qLimXkEOoJgHWDHiNhxUXGXgA62qavaIVklJxt.

Dashboard DT view: https://vlad.try.gravitykit.com/wp-admin/edit.php?post_type=gravityview&page=dashboard_views&gvid=1562&mode=any

DT view: https://vlad.try.gravitykit.com/view/dashboard-views-dt/

**Comment by zackkatz** [comment]
Seems to be working @mrcasual
