### ISSUE TITLE
Issue to gather interest

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/Dashboard-Views#8]
Currently, there are 33 tickets 👍 

https://support.gravitykit.com/search?f%5Btag%5D=use%20case:%20dashboard%20views
https://secure.helpscout.net/search/?query=tag%3Adashboard
https://secure.helpscout.net/search/?query=tag%3Ause%20case%3A%20dashboard
https://secure.helpscout.net/search/?query=tag%3Ause%20case%3A%20dashboard%20views

**Comment by rafaehlers** [comment]
All customers notified ✅
