### ISSUE TITLE
Create a setting to add Dashboard View to the WP sidebar menu

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/Dashboard-Views#9]
Ehlers says that the biggest annoyance is having to go into Views and clicking on a link.

This should add a setting to a View's `Settings` metabox.

- [x] Create a new Dashboard Views tab
- Add settings for:
  - [x] Location
  - [x] Label
  - [x] Capability

OR 

- [ ] Create a global setting where Views can be selected and configured as above.

**Comment by mrcasual** [comment]
@rafaehlers, @zackkatz, what should these settings do:

> * [ ]  Create a new Dashboard Views tab
> * Add settings for:
>   
>   * [ ]  Location
>   * [ ]  Label

**Comment by rafaehlers** [comment]
@mrcasual 
"Create a new Dashboard Views tab" inside Foundation.
"Location" refers to the location of the new menu/page (that hasn't be defined yet) that's going to be created just for Dashboard Views.
"Label" of the link in the menu/page where a customer can customize, like "Reports".

**Comment by zackkatz** [comment]
Added in 2.0
